# ============================================================
# criar-tabela.ps1 - Cria a tabela 'pontuacoes' no Supabase
#
# Uso:
#   powershell -ExecutionPolicy Bypass -File criar-tabela.ps1 -Pat SEU_TOKEN
#
# Como obter o token (gratuito, 1 minuto):
#   1. Acesse https://supabase.com/dashboard/account/tokens
#   2. Clique em "Generate new token" e copie
# ============================================================
param(
    [Parameter(Mandatory = $true)]
    [string]$Pat
)

$ErrorActionPreference = "Stop"
$ProjectRef = "vpzxrmxqkjrkxhzodovg"
$ApiUrl = "https://api.supabase.com/v1/projects/$ProjectRef/database/query"

# ATENCAO: a Management API exige o PERSONAL ACCESS TOKEN (nao a anon key!)
$sql = @'
create table if not exists pontuacoes (
  id bigint generated by default as identity primary key,
  nome text not null,
  pontuacao int not null,
  criado_em timestamptz default now()
);

alter table pontuacoes enable row level security;

drop policy if exists "insert publico" on pontuacoes;
drop policy if exists "select publico" on pontuacoes;

create policy "insert publico" on pontuacoes
  for insert to anon with check (true);

create policy "select publico" on pontuacoes
  for select to anon using (true);
'@

Write-Host "Criando tabela 'pontuacoes' no projeto $ProjectRef ..." -ForegroundColor Cyan

try {
    $body = @{ query = $sql } | ConvertTo-Json
    $resp = Invoke-RestMethod -Method Post -Uri $ApiUrl -Headers @{ Authorization = "Bearer $Pat" } -ContentType "application/json" -Body $body

    Write-Host "[OK] Tabela criada com sucesso!" -ForegroundColor Green
    if ($resp) { $resp | ConvertTo-Json -Depth 5 }
    Write-Host ""
    Write-Host "Pronto! O placar global do Flappy Link esta no ar."
    Write-Host "Teste: jogue uma partida e veja o ranking no Game Over."
} catch {
    Write-Host "[ERRO] Nao foi possivel criar a tabela:" -ForegroundColor Red
    Write-Host $_.Exception.Message
    Write-Host ""
    Write-Host "Dicas:" -ForegroundColor Yellow
    Write-Host " - O token deve ser o PERSONAL ACCESS TOKEN (https://supabase.com/dashboard/account/tokens)"
    Write-Host " - Alternativa manual: cole o conteudo de criar-tabela.sql no SQL Editor do"
    Write-Host "   painel do Supabase e clique em RUN."
    exit 1
}
