-- ============================================================
-- Tabela do placar global — cole no SQL Editor do Supabase
-- (https://supabase.com/dashboard/project/vpzxrmxqkjrkxhzodovg/sql/new)
-- e clique em RUN. Alternativa: rodar criar-tabela.ps1 com um PAT.
-- ============================================================
create table if not exists pontuacoes (
  id bigint generated by default as identity primary key,
  nome text not null,
  pontuacao int not null,
  criado_em timestamptz default now()
);

alter table pontuacoes enable row level security;

drop policy if exists "insert publico" on pontuacoes;
drop policy if exists "select publico" on pontuacoes;

create policy "insert publico" on pontuacoes
  for insert to anon with check (true);

create policy "select publico" on pontuacoes
  for select to anon using (true);
